BUILT IN FUNCTIONS IN NUMPY

MATHEMATICAL FUNCTIONS:SIN, COS, TAN, SQRT AND LOG

In [7]:
import numpy as np
a =np.array =([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [9]:
print(np.cos(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [11]:
print(np.tan(a))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [13]:
print(np.exp(a))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [14]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [15]:
print(np.log(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [2]:
a.mean()

NameError: name 'a' is not defined

AGGREGATE FUNCTIONS:.SUM, .MAX, .MIN


In [6]:
import numpy as np
b = np.arange(12).reshape(3,4)
print(b)
b.sum()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


66

In [27]:
print(b.max())

11


In [30]:
print(b.min())

0


In [7]:
print(b.sum(axis = 0)) # sum of each column


[12 15 18 21]


In [33]:
print(b.cumsum(axis = 1)) # cummulative sum along each row

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [8]:
print(b.sum(axis =1))# sum along rows

[ 6 22 38]


In [10]:
print(b.argmin()) #gives index of minimum nuber
print(b.argmax()) #gives index of maximum number

0
11


In [41]:
my_list = b.tolist() #converts array to list
print(my_list)
print(type(my_list))

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
<class 'list'>


In [42]:
array_swapped = np.swapaxes(b,0,1)
print(array_swapped)


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [2]:
import numpy as np
c= np.array([
            [1,5,9],
            [2,3,4]
            ])
print(c)


[[1 5 9]
 [2 3 4]]


In [33]:
c.reshape(c.size)

array([1, 5, 9, 2, 3, 4])

In [39]:
array_diagonal = np.diagonal(c)
print(array_diagonal)

[1 3]


In [34]:
array_repeat = np.repeat(120,3)
print(array_repeat)

[120 120 120]


In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

FUNCTIONS IN PANDAS

1. Reading a file

In [ ]:
import panda as pd
df = pd.read_csv('texted.csv')

2. Get the top and bottom of data set

In [ ]:
df.head()
df.tail()

3. Get the complete information about all the columns in the table

In [ ]:
df.info()

4. Shape and resize of dataset

In [ ]:
df.shape()
df.size()

5. Choose n number of random sample from dataset 

In [ ]:
df.sample(n=10)

In [ ]:
df.describe()
df.describe().T