<a href="https://colab.research.google.com/github/blessingajidahun/WTF-Submission/blob/main/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)
print (a.dtype)
print(a.ndim)

(4,)
int64
1


In [ ]:
b = np.array([[1,2,3,4], [5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(b.ndim)
print(b.shape)

2
(2, 4)


In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
print(b.dtype)

int64


In [2]:
import numpy as np

In [5]:
c = np.array ([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [23]:
arr = c.reshape(3,4)
print(arr)

print(arr[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]


In [52]:
print(type(arr))

<class 'numpy.ndarray'>


In [25]:
print(arr[2,:2])

[ 9 10]


In [ ]:
d = c.reshape(2,6)
print(d)

In [ ]:
d = c.reshape(3,4,1)
print(d)

Random function

In [ ]:
random_int= np.random.randint(100)
print(random_int)

Generate a 1-D array containing 5 random integers from 0 to 100

In [32]:
random_array = np.random.randint(100, size = (5))
print(random_array)

[28  2 77 69 24]


Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

In [33]:
a= np.random.randint(50, size = (3,5))
print(a)

[[46 44 30  5 16]
 [49 49 39 37 23]
 [19 17 36 13 44]]


The rand() method is used to generate random floating point numbers between 0 and 1. It also allows you to specify the shape of the array.
To Generate a 1-D array containing 5 random floats:

In [34]:
x = np.random.rand(5)
print(x)

[0.81140248 0.10712104 0.81615024 0.80001393 0.69607169]


Genearte a 2d array containing 3 rows with 4 columns each

In [ ]:
x = np.random.rand(3,4)
print(x)

In [43]:
np.random.random((2,3))


array([[0.48998123, 0.1850498 , 0.0265156 ],
       [0.24893999, 0.8664507 , 0.45790052]])

In [44]:
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])
print(c+d)

[[13. 13. 13.]
 [10. 10. 10.]]


In [50]:
print(c*d)
print(c**2)

[[36. 40. 42.]
 [ 9. 16. 21.]]
[[81. 64. 49.]
 [ 1.  4.  9.]]


In [56]:
print(d[1,2])

7.0


Indexing in numpy

In [57]:
e = np.array([[10,11,12], [13,14,15], [16,17,18], [19,20,21]])
print(e.shape)
print(e.ndim)

(4, 3)
2


In [58]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [59]:
e[[2,0,3,1], [2,1,0,2]]

array([18, 11, 19, 15])